spring.application.name=matricula-segura
server.port=8080

#Configurar dataSource
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/matricula
spring.datasource.username=root
spring.datasource.password=root
#Configurar JPA
spring.jpa.database=MYSQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#Configuracion de security

#spring.security.user.name=admin
#spring.security.user.password=admin

#Configuracion JWT
security.jwt.secret-key=MI-LLAVE-PARA-VARIAS-APLICACIONES
