spring.application.name=servidoreureka
#EUREKA CONFIG
server.port=8761
##server.port=8766
#Propiedades de eureka para desactivar el auto registro y la obtención del registro
#Que se registre a si mismo como cliente
eureka.client.register-with-eureka=true
#Que obtenga el registro de otros servicios
eureka.client.fetch-registry=true
#Hostname de la instancia (milocalhost)
eureka.instance.hostname=hostname
#Preferir IP en lugar de hostname
eureka.instance.prefer-ip-address=true

# Forzar que el ID de la instancia (lo que se muestra en la UI de Eureka)
# use el hostname configurado arriba en vez del hostname del SO
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}

#Propiedades eureka para monitorear el estado de los servicios
#Habilitar la autoprotectión para evitar que Eureka marque como no disponibles los servicios que no renueven su registro a tiempo
eureka.server.enable-self-preservation=true
#Definir el intervalo esperado de renovación del cliente en segundos
eureka.server.expected-client-renewal-interval-seconds=30
#Definir el umbral de renovación del cliente en porcentaje
eureka.server.renewal-percent-threshold=0.85
##eureka.client.service-url.defaultZone=http://milocalhost:8766/eureka/, http://localhost:8761/eureka
