spring.application.name=producer
server.port=8082

# Configuración de la base de datos
## URL de la clase del driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## Cadena de conexión
spring.datasource.url=jdbc:mysql://localhost:3306/matricula
## Usuario de la BD
spring.datasource.username=root
## Password de la BD
spring.datasource.password=root
# Configuración de JPA/Hibernate
## Motor de BD utilizado
spring.jpa.database=mysql
## Habilitar la ejecución de sentencias DDL automaticas
spring.jpa.hibernate.ddl-auto=none
## Habilitar que se muestre en consola la ejecución de sentencias SQL
spring.jpa.show-sql=false
## Habilitar en que formato se mostrarán las sentencias SQL
spring.jpa.properties.hibernate.format_sql=true

#Configuraciones de kafka consumer
##Configura la url de Kafka
spring.kafka.bootstrap-servers=localhost:9092
##Configura el grupo de consumidores
spring.kafka.consumer.group-id=grupo-consumidor-curso
##Configura para que la confirmacion de la lectura del mensaje sea automatica
spring.kafka.consumer.enable-auto-commit=false
##Configura el tiempo de espera para la confirmacion de lectura del mensaje
spring.kafka.consumer.auto-offset-reset=earliest
##Configura el intervalo de auto-commit
spring.kafka.consumer.auto-commit-interval=1000
##Configura el maximo de mensajes a leer en cada poll
spring.kafka.consumer.max-poll-records=1
#Configuraciones de las propiedades del consumidor
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.topico.nombre=curso-topico