spring.application.name=api-carrito
server.port=8080

##Configurar dataSource
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/carrito
#spring.datasource.username=root
#spring.datasource.password=root
##Configurar JPA
#spring.jpa.database=MYSQL
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
#Configuración del dataSource reactivos
spring.r2dbc.url=r2dbc:mysql://localhost:3306/carrito
spring.r2dbc.username=root
spring.r2dbc.password=082022fF
spring.sql.init.platform=mysql
#spring.r2dbc.driver=io.r2dbc.mysql.R2DBCMySQLDriver

#Swagger Config
#Configuracion de SpringDoc OpenAPI
springdoc.api-docs.path=/api-docs
#Configuracion de Swagger Interface de usuario
springdoc.swagger-ui.path=/
springdoc.swagger-ui.enabled=true
#Confguracion para ordernar los endpoints
springdoc.swagger-ui.operationsSorter=alpha
#Configuracion de la informacion de la API
springdoc.open-api.info.title=TITULO DE MI API
springdoc.open-api.info.description=DESCRIPCION DE MI API
springdoc.open-api.info.version=1.0
springdoc.open-api.info.contact.name=JUAN CARLOS PEREZ GIL
springdoc.open-api.info.contact.email=JPEREZGIL@OUTLOOK.COM
springdoc.open-api.info.contact.url=https://www.linkedin.com/in/jperezgi
springdoc.open-api.info.license.name=LICENCIA DE MI API
springdoc.open-api.info.license.url=URL LICENCIA DE MI API

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#Fuerzo para reconosca los el HOST y el INSTANCE-ID
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false