#Variables de entorno
spring.application.name=MATRICULA
server.port=8090

#Configuraciones del log de servidor
server.tomcat.basedir=c:/temp/tomcat
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D
server.tomcat.accesslog.prefix=access_log
server.tomcat.accesslog.suffix=.log

#Parametros personalizados
mensaje.bienvenida=Bienvenido al sistema de matriculas
