spring.application.name=jbc6laboratorio1
server.port=8082
#DataSource Config
spring.datasource.url=jdbc:mysql://localhost:3306/matricula
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#JPA Config
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.fomat_sql=true

#Confgiruacion de la llave de seguridad del jwt  // tener cuidado con el tamaño de la llave tiene que ser mayor a 256 bits
security.jwt.secret-key=MI-LLAVE-PARA-VARIAS-APLICACIONES