spring.application.name=api-seguridad-oauth2
#Configurar dataSource
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/matricula
spring.datasource.username=root
spring.datasource.password=082022fF
#Configurar JPA
spring.jpa.database=MYSQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Configuración del servidor
server.port=8080
server.servlet.context-path=/

# Configuración OAuth2 Authorization Server
security.oauth2.client.id=admin
security.oauth2.client.secret=admin

# Configuración JWT para Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080