spring.application.name=apim
server.port=8079

##CONFIGURACIONES DE EUREKA CLIENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#Fuerzo para reconosca los el HOST y el INSTANCE-ID
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

##CONFIGURACIONES DEL API GATEWAY
spring.main.web-application-type=reactive
#Configuracion api gateway routes[0]
spring.cloud.gateway.server.webflux.routes[0].id=productos
spring.cloud.gateway.server.webflux.routes[0].uri=lb://APICARRITO
spring.cloud.gateway.server.webflux.routes[0].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[0].predicates[0].args[pattern]=/api/productos/**
#Configuracion api gateway routes[1]
spring.cloud.gateway.server.webflux.routes[1].id=categorias
spring.cloud.gateway.server.webflux.routes[1].uri=lb://APICARRITO
spring.cloud.gateway.server.webflux.routes[1].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[1].predicates[0].args[pattern]=/api/categorias/**
#Configuracion api gateway routes[2]
spring.cloud.gateway.server.webflux.routes[2].id=usuarios
spring.cloud.gateway.server.webflux.routes[2].uri=lb://APICARRITO
spring.cloud.gateway.server.webflux.routes[2].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[2].predicates[0].args[pattern]=/api/usuarios/**
#Configuracion api gateway routes[3]
spring.cloud.gateway.server.webflux.routes[3].id=seguridad
spring.cloud.gateway.server.webflux.routes[3].uri=lb://APISEGURIDAD
spring.cloud.gateway.server.webflux.routes[3].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[3].predicates[0].args[pattern]=/api/security/**
#Personalizar el tipo de balanceo
#spring.cloud.loadbalancer.health-check.interval=10s
spring.cloud.loadbalancer.enabled=true

#Confgiruacion de la llave de seguridad del jwt  // tener cuidado con el tamaño de la llave tiene que ser mayor a 256 bits
security.jwt.secret-key=MI-LLAVE-PARA-VARIAS-APLICACIONES