#Eureka client
##Indicar el nombre de la aplicacion para el registro en Eureka
spring.application.name=apim
##Indicar el puerto donde se ejecutara la aplicacion
server.port=8080
##Indicar la url del servidor Eureka para el registro de servicios
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#Indicar el Hostname donde esta la aplicacion
eureka.instance.hostname=localhost
##Personalizar el id de la instancia 
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}

#URL DE MICROSERVICIO DE MATRICULA
matricula.url=http://apimatricula/api/usuarios

#URL DE MICROSERVICIO DE USUARIO
usuarios.url=http://apiusuario/api/usuarios

##USANDO UNA LIBRERIA (Si se usa esta libreria deja de funcionar lo del controlador)
#Agregar si van a utilizar spring cloud gateway con spring web
spring.main.web-application-type=reactive

#Configuracion api gateway routes[0]
spring.cloud.gateway.server.webflux.routes[0].id=api-matricula
spring.cloud.gateway.server.webflux.routes[0].uri=lb://APIMATRICULA
spring.cloud.gateway.server.webflux.routes[0].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[0].predicates[0].args[pattern]=/matriculas/**
#Configuracion api gateway routes[1]
spring.cloud.gateway.server.webflux.routes[1].id=api-curso
spring.cloud.gateway.server.webflux.routes[1].uri=lb://APIMATRICULA
spring.cloud.gateway.server.webflux.routes[1].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[1].predicates[0].args[pattern]=/cursos/**
#Configuracion api gateway routes[2]
spring.cloud.gateway.server.webflux.routes[2].id=api-usuario
spring.cloud.gateway.server.webflux.routes[2].uri=lb://APIUSUARIO
spring.cloud.gateway.server.webflux.routes[2].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[2].predicates[0].args[pattern]=/api/usuarios/**

#Personalizar el tipo de balanceo
#spring.cloud.loadbalancer.health-check.interval=10s
spring.cloud.loadbalancer.enabled=true