spring.application.name=webmatricula

# Configuración de la base de datos
## URL de la clase del driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## Cadena de conexión
spring.datasource.url=jdbc:mysql://localhost:3306/matricula
## Usuario de la BD
spring.datasource.username=root
## Password de la BD
spring.datasource.password=root
# Configuración de JPA/Hibernate
## Motor de BD utilizado
spring.jpa.database=mysql
## Habilitar la ejecución de sentencias DDL automaticas
spring.jpa.hibernate.ddl-auto=none
## Habilitar que se muestre en consola la ejecución de sentencias SQL
spring.jpa.show-sql=false
## Habilitar en que formato se mostrarán las sentencias SQL
spring.jpa.properties.hibernate.format_sql=true

#Configuracion Spring Security
##Si no se configura te crea un usuario por efecto (user) y te genera una contraseña aleatoria
##Sin yo configuro el usario, contraseña y rol por el archivo propertis entonces se habilita el login con ese usuario y contraseña definido aqui
###spring.security.user.name=admin
###spring.security.user.password=admin
###spring.security.user.roles=ADMIN